/**
 * File storage.
 *
 * Datasets, generated reports and chart images live on disk under a single
 * configured root. Two rules are enforced here rather than left to callers:
 *
 *   1. Every stored name is generated by this module, never taken from a
 *      request. A path that could escape the storage root is rejected.
 *   2. Nothing is served from a guessable public path. Reads go through
 *      `readStoredFile`, which is only reachable from an authenticated route.
 *
 * An S3-compatible provider can be substituted by implementing `StorageProvider`
 * and selecting it through STORAGE_PROVIDER. The local provider is the only one
 * implemented and tested; the interface exists so the substitution has one
 * obvious place to happen.
 */

import "server-only";

import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { AppError } from "./api";
import { env } from "./env";

export type StorageProviderName = "local" | "s3";

export interface StoredObject {
  /** Path relative to the storage root. Never absolute, never user-supplied. */
  relativePath: string;
  sizeBytes: number;
  sha256: string;
  contentType: string;
}

export interface StorageProvider {
  readonly name: StorageProviderName;
  put(
    scope: string,
    filename: string,
    body: Buffer,
    contentType: string,
  ): Promise<StoredObject>;
  get(relativePath: string): Promise<Buffer>;
  remove(relativePath: string): Promise<void>;
  exists(relativePath: string): Promise<boolean>;
}

/** Characters permitted in a stored filename. */
const SAFE_NAME = /^[A-Za-z0-9._-]+$/;

/**
 * Absolute path of the storage root.
 *
 * The directory is chosen at runtime from configuration, so the bundler cannot
 * statically resolve it. The ignore marker is deliberate: without it the
 * bundler conservatively traces the entire project into the server output
 * because it assumes any reachable file might be read. The path is still
 * constrained to the storage root by `safeRelative` below.
 */
function root(): string {
  return path.resolve(/* turbopackIgnore: true */ process.cwd(), env.storageDir);
}

/**
 * Split a stored relative path into its segments.
 *
 * Both separators are accepted. A path is built with `path.join`, which
 * produces a backslash on Windows, and is then stored in the database. Reading
 * it back on Windows would otherwise yield one segment containing a backslash,
 * which the character filter rejects — so an upload could be written but never
 * read again. Accepting both separators means a path written on one platform is
 * readable on another.
 */
export function splitStoredPath(relativePath: string): string[] {
  return relativePath.split(/[\\/]+/).filter((part) => part.length > 0);
}

/**
 * Build a safe relative path and prove it stays inside the storage root.
 *
 * The resolve-and-compare step is the actual defence. Filtering characters is a
 * convenience; this is what makes traversal impossible.
 *
 * Returns a POSIX-style path. The path is persisted in the database, so it has
 * to mean the same thing on every platform rather than carrying whichever
 * separator the writing machine happened to use.
 */
function safeRelative(parts: string[]): string {
  for (const part of parts) {
    if (!SAFE_NAME.test(part)) {
      throw AppError.badRequest(
        "The storage path contains characters that are not allowed.",
        { code: "invalid_storage_path" },
      );
    }
  }
  const relative = parts.join("/");
  const absolute = path.resolve(
    /* turbopackIgnore: true */ root(),
    ...parts,
  );
  const base = root();
  if (absolute !== base && !absolute.startsWith(base + path.sep)) {
    throw AppError.badRequest(
      "The storage path points outside the storage directory.",
      { code: "path_traversal_blocked" },
    );
  }
  return relative;
}

class LocalStorageProvider implements StorageProvider {
  readonly name = "local" as const;

  async put(
    scope: string,
    filename: string,
    body: Buffer,
    contentType: string,
  ): Promise<StoredObject> {
    const relative = safeRelative([scope, filename]);
    const absolute = path.resolve(/* turbopackIgnore: true */ root(), relative);
    await mkdir(path.dirname(absolute), { recursive: true });
    await writeFile(absolute, body);
    return {
      relativePath: relative,
      sizeBytes: body.byteLength,
      sha256: createHash("sha256").update(body).digest("hex"),
      contentType,
    };
  }

  async get(relativePath: string): Promise<Buffer> {
    const relative = safeRelative(splitStoredPath(relativePath));
    return readFile(path.resolve(/* turbopackIgnore: true */ root(), relative));
  }

  async remove(relativePath: string): Promise<void> {
    const relative = safeRelative(splitStoredPath(relativePath));
    await rm(path.resolve(/* turbopackIgnore: true */ root(), relative), {
      force: true,
    });
  }

  async exists(relativePath: string): Promise<boolean> {
    try {
      const relative = safeRelative(splitStoredPath(relativePath));
      await stat(path.resolve(/* turbopackIgnore: true */ root(), relative));
      return true;
    } catch {
      return false;
    }
  }
}

const local = new LocalStorageProvider();

export function storage(): StorageProvider {
  // Only the local provider is implemented. Selecting s3 without an
  // implementation is a configuration error, not something to paper over.
  return local;
}

/** A filename that cannot collide and cannot be guessed from user input. */
export function generatedName(prefix: string, extension: string): string {
  const random = createHash("sha256")
    .update(`${prefix}:${Date.now()}:${Math.random()}`)
    .digest("hex")
    .slice(0, 24);
  const cleanPrefix = prefix.replace(/[^A-Za-z0-9._-]/g, "").slice(0, 40) || "file";
  return `${cleanPrefix}-${random}${extension.startsWith(".") ? extension : `.${extension}`}`;
}

export const CONTENT_TYPES: Record<string, string> = {
  csv: "text/csv; charset=utf-8",
  json: "application/json; charset=utf-8",
  pdf: "application/pdf",
  png: "image/png",
  joblib: "application/octet-stream",
};

export function extensionFor(filename: string): string {
  const index = filename.lastIndexOf(".");
  return index > 0 ? filename.slice(index).toLowerCase() : "";
}

export function sha256(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}
