/**
 * A synthetic population of Telco customers.
 *
 * The real dataset is 7,043 rows of a known churn benchmark. For the simulated
 * frontend we need a population with the same shape, so pages that depend on
 * distributions look right, but we also need each row's risk to be
 * *explainable*.
 *
 * The trick that keeps everything consistent: churn risk is generated by an
 * explicit linear model over the customer's own attributes. A row's score is
 * therefore a sum of per-feature contributions plus a base value, exactly. The
 * explanations on the detail pages are that same decomposition, not a separate
 * invention, so a prediction and its waterfall cannot disagree.
 *
 * The realised churn rate is pinned to the real dataset's 26.54% by solving for
 * the intercept, so aggregate figures match what someone would expect from the
 * genuine file.
 */

import { Rng, logit, sigmoid, solveIntercept } from "./rng";

export const POPULATION_SIZE = 7043;
export const TARGET_CHURN_RATE = 0.26536987;

export type ContractType = "Month-to-month" | "One year" | "Two year";
export type InternetService = "DSL" | "Fiber optic" | "No";
export type PaymentMethod =
  | "Electronic check"
  | "Credit card"
  | "Bank transfer"
  | "Mailed check";
export type YesNo = "Yes" | "No";

export interface Customer {
  index: number;
  customerId: string;
  gender: "Male" | "Female";
  seniorCitizen: 0 | 1;
  partner: YesNo;
  dependents: YesNo;
  tenureMonths: number;
  phoneService: YesNo;
  multipleLines: YesNo;
  internetService: InternetService;
  onlineSecurity: YesNo;
  onlineBackup: YesNo;
  techSupport: YesNo;
  streamingTv: YesNo;
  streamingMovies: YesNo;
  contract: ContractType;
  paperlessBilling: YesNo;
  paymentMethod: PaymentMethod;
  monthlyCharges: number;
  totalCharges: number | null;
  /** Observed outcome, as if the customer really had churned. */
  churned: 0 | 1;
  /** Latent churn probability before any model noise. */
  baseProbability: number;
  /**
   * Tenure bands drive every chart on the dashboard, so the boundaries are
   * shared here rather than repeated at each call site.
   */
  tenureBand: string;
}

/**
 * Per-feature weight on the log-odds scale.
 *
 * The signs follow what is documented as the strongest driver in this dataset:
 * month-to-month contracts, long tenure and two-year contracts reduce risk,
 * while fibre, electronic-check payment and no tech support raise it.
 */
export const FEATURE_WEIGHTS = {
  "Contract: Month-to-month": 1.62,
  "Contract: One year": -0.44,
  "Contract: Two year": -1.21,
  "InternetService: Fiber optic": 0.88,
  "InternetService: No": -0.51,
  "OnlineSecurity: No": 0.62,
  "TechSupport: No": 0.49,
  "PaymentMethod: Electronic check": 0.74,
  "PaymentMethod: Bank transfer": -0.22,
  "PaperlessBilling: Yes": 0.31,
  "MultipleLines: Yes": 0.19,
  "Dependents: Yes": -0.27,
  "SeniorCitizen: 1": 0.24,
  "tenure: short": 0.58,
  "tenure: medium": 0.12,
  "tenure: long": -0.94,
  "MonthlyCharges: high": 0.34,
} as const;

export type WeightedFeature = keyof typeof FEATURE_WEIGHTS;

const TENURE_BANDS = [
  { label: "0-6 months", max: 6 },
  { label: "7-12 months", max: 12 },
  { label: "13-24 months", max: 24 },
  { label: "25-48 months", max: 48 },
  { label: "49+ months", max: Number.POSITIVE_INFINITY },
] as const;

function tenureBand(tenure: number): string {
  for (const band of TENURE_BANDS) {
    if (tenure <= band.max) return band.label;
  }
  return "49+ months";
}

/** The zero-month bucket churns at a very different rate, so it is separate. */
function tenureFeature(tenure: number): WeightedFeature {
  if (tenure <= 12) return "tenure: short";
  if (tenure <= 48) return "tenure: medium";
  return "tenure: long";
}

/** Everyone without internet also lacks these add-ons. */
/** The subset of features whose contribution varies per customer. */
function activeFeatures(customer: Omit<Customer, "churned" | "baseProbability">): {
  feature: WeightedFeature;
  contribution: number;
}[] {
  const active: { feature: WeightedFeature; contribution: number }[] = [];

  if (customer.contract === "Month-to-month") {
    active.push({
      feature: "Contract: Month-to-month",
      contribution: FEATURE_WEIGHTS["Contract: Month-to-month"],
    });
  } else if (customer.contract === "One year") {
    active.push({
      feature: "Contract: One year",
      contribution: FEATURE_WEIGHTS["Contract: One year"],
    });
  } else {
    active.push({
      feature: "Contract: Two year",
      contribution: FEATURE_WEIGHTS["Contract: Two year"],
    });
  }

  if (customer.internetService === "Fiber optic") {
    active.push({
      feature: "InternetService: Fiber optic",
      contribution: FEATURE_WEIGHTS["InternetService: Fiber optic"],
    });
  } else if (customer.internetService === "No") {
    active.push({
      feature: "InternetService: No",
      contribution: FEATURE_WEIGHTS["InternetService: No"],
    });
  }

  if (customer.internetService !== "No" && customer.onlineSecurity === "No") {
    active.push({
      feature: "OnlineSecurity: No",
      contribution: FEATURE_WEIGHTS["OnlineSecurity: No"],
    });
  }

  if (customer.internetService !== "No" && customer.techSupport === "No") {
    active.push({
      feature: "TechSupport: No",
      contribution: FEATURE_WEIGHTS["TechSupport: No"],
    });
  }

  if (customer.paymentMethod === "Electronic check") {
    active.push({
      feature: "PaymentMethod: Electronic check",
      contribution: FEATURE_WEIGHTS["PaymentMethod: Electronic check"],
    });
  } else if (customer.paymentMethod === "Bank transfer") {
    active.push({
      feature: "PaymentMethod: Bank transfer",
      contribution: FEATURE_WEIGHTS["PaymentMethod: Bank transfer"],
    });
  }

  if (customer.paperlessBilling === "Yes") {
    active.push({
      feature: "PaperlessBilling: Yes",
      contribution: FEATURE_WEIGHTS["PaperlessBilling: Yes"],
    });
  }

  if (customer.multipleLines === "Yes" && customer.phoneService === "Yes") {
    active.push({
      feature: "MultipleLines: Yes",
      contribution: FEATURE_WEIGHTS["MultipleLines: Yes"],
    });
  }

  if (customer.dependents === "Yes") {
    active.push({
      feature: "Dependents: Yes",
      contribution: FEATURE_WEIGHTS["Dependents: Yes"],
    });
  }

  if (customer.seniorCitizen === 1) {
    active.push({
      feature: "SeniorCitizen: 1",
      contribution: FEATURE_WEIGHTS["SeniorCitizen: 1"],
    });
  }

  active.push({
    feature: tenureFeature(customer.tenureMonths),
    contribution: FEATURE_WEIGHTS[tenureFeature(customer.tenureMonths)],
  });

  if (customer.monthlyCharges >= 80) {
    active.push({
      feature: "MonthlyCharges: high",
      contribution: FEATURE_WEIGHTS["MonthlyCharges: high"],
    });
  }

  return active;
}

/** Human-readable labels, so explanation rows are not raw column names. */
const FEATURE_LABELS: Record<string, string> = {
  "Contract: Month-to-month": "Contract: Month-to-month",
  "Contract: One year": "Contract: One year",
  "Contract: Two year": "Contract: Two year",
  "InternetService: Fiber optic": "Internet service: Fibre optic",
  "InternetService: No": "Internet service: None",
  "OnlineSecurity: No": "Online security: No",
  "TechSupport: No": "Tech support: No",
  "PaymentMethod: Electronic check": "Payment method: Electronic check",
  "PaymentMethod: Bank transfer": "Payment method: Bank transfer",
  "PaperlessBilling: Yes": "Paperless billing: Yes",
  "MultipleLines: Yes": "Multiple lines: Yes",
  "Dependents: Yes": "Dependents: Yes",
  "SeniorCitizen: 1": "Senior citizen: Yes",
  "tenure: short": "Tenure: 12 months or less",
  "tenure: medium": "Tenure: 13 to 48 months",
  "tenure: long": "Tenure: over 48 months",
  "MonthlyCharges: high": "Monthly charges: $80 or more",
};

export function featureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}

export function featureSourceColumn(feature: string): string {
  const [group, tail] = feature.split(": ");
  if (group === "tenure") return "tenure";
  if (group === "MonthlyCharges") return "MonthlyCharges";
  if (group === "PaperlessBilling") return "PaperlessBilling";
  if (group === "Dependents") return "Dependents";
  if (group === "SeniorCitizen") return "SeniorCitizen";
  if (group === "MultipleLines") return "MultipleLines";
  if (group === "PaymentMethod") return "PaymentMethod";
  if (group === "TechSupport") return "TechSupport";
  if (group === "OnlineSecurity") return "OnlineSecurity";
  if (group === "InternetService") return "InternetService";
  if (group === "Contract") return "Contract";
  return tail ?? group;
}

export function featureKind(feature: string): string {
  const column = featureSourceColumn(feature);
  if (["tenure", "MonthlyCharges"].includes(column)) return "numeric";
  if (column === "SeniorCitizen") return "binary";
  return "categorical";
}

/**
 * Generate one customer's attributes, and its weighted risk term.
 *
 * The probability and the observed outcome are assigned afterwards, once the
 * intercept is known. Labelling here would need an intercept that is itself
 * derived from the whole population, so it cannot be done one row at a time.
 */
function generateDraft(
  rng: Rng,
  index: number,
): { draft: Omit<Customer, "churned" | "baseProbability">; term: number } {
  const gender = rng.weighted([
    ["Male", 0.5249],
    ["Female", 0.4751],
  ] as const);

  const internetService = rng.weighted([
    ["Fiber optic", 0.431],
    ["DSL", 0.3446],
    ["No", 0.2244],
  ] as const) as InternetService;

  // Long-tenure customers are far more likely to be on a two-year contract,
  // which is why contract and tenure are correlated in the real data.
  const tenureMonths =
    rng.chance(0.2) ? rng.int(0, 6) : rng.chance(0.45) ? rng.int(1, 24) : rng.int(1, 72);

  const contract = rng.weighted([
    ["Month-to-month", tenureMonths <= 12 ? 0.79 : tenureMonths <= 24 ? 0.55 : 0.3],
    ["One year", tenureMonths <= 12 ? 0.15 : 0.35],
    ["Two year", tenureMonths <= 12 ? 0.06 : 0.35],
  ] as const) as ContractType;

  const phoneService: YesNo = rng.chance(0.9015) ? "Yes" : "No";

  const baseMonthly =
    internetService === "Fiber optic" ? 70.4 : internetService === "DSL" ? 56.3 : 21.2;
  const monthlyCharges =
    Math.round((baseMonthly + rng.float(-8, 18) + (contract === "Two year" ? -3 : 0)) * 100) /
    100;

  // The real file has 11 blank TotalCharges, all with zero tenure, so they are
  // reproduced rather than spread across the population.
  const hasBlankCharges = tenureMonths === 0 && rng.chance(0.0754);
  const totalCharges = hasBlankCharges
    ? null
    : Math.round(monthlyCharges * tenureMonths * 100) / 100;

  const draft: Omit<Customer, "churned" | "baseProbability"> = {
    index,
    customerId: String(1000 + index),
    gender,
    seniorCitizen: rng.chance(0.382) ? 1 : 0,
    partner: rng.chance(0.5153) ? "Yes" : "No",
    dependents: rng.chance(0.462) ? "Yes" : "No",
    tenureMonths,
    phoneService,
    multipleLines: phoneService === "Yes" && rng.chance(0.4269) ? "Yes" : "No",
    internetService,
    onlineSecurity: internetService === "No" ? "No" : rng.chance(0.2837) ? "Yes" : "No",
    onlineBackup: internetService === "No" ? "No" : rng.chance(0.271) ? "Yes" : "No",
    techSupport: internetService === "No" ? "No" : rng.chance(0.2909) ? "Yes" : "No",
    streamingTv: internetService === "No" ? "No" : rng.chance(0.2005) ? "Yes" : "No",
    streamingMovies: internetService === "No" ? "No" : rng.chance(0.2012) ? "Yes" : "No",
    contract,
    paperlessBilling: rng.chance(0.5927) ? "Yes" : "No",
    paymentMethod: rng.weighted([
      ["Electronic check", 0.3365],
      ["Credit card", 0.2715],
      ["Bank transfer", 0.2439],
      ["Mailed check", 0.1481],
    ] as const) as PaymentMethod,
    monthlyCharges,
    totalCharges,
    tenureBand: tenureBand(tenureMonths),
  };

  const term = activeFeatures(draft).reduce(
    (sum, entry) => sum + entry.contribution,
    0,
  );
  return { draft, term };
}

export interface Population {
  customers: Customer[];
  /** The intercept that pins the churn rate, reused for base values. */
  intercept: number;
  /** Mean log-odds across the population, used as the SHAP base value. */
  baseValue: number;
  realisedChurnRate: number;
}

/**
 * Build the whole population. Same seed, same world, every time.
 *
 * The intercept is solved from the finished attributes rather than assumed, so
 * the average predicted probability lands on the target churn rate and the
 * scores are calibrated to the dataset they claim to describe.
 */
export function buildPopulation(seed = "telco-demo-v1"): Population {
  const rng = new Rng(seed);
  const drafts = Array.from({ length: POPULATION_SIZE }, (_, index) =>
    generateDraft(rng.fork(`c${index}`), index),
  );
  const intercept = solveIntercept(
    drafts.map((entry) => entry.term),
    TARGET_CHURN_RATE,
  );

  const customers: Customer[] = drafts.map(({ draft, term }, index) => {
    const baseProbability = sigmoid(intercept + term);
    // The label is drawn after the intercept is fixed, so the realised rate
    // lands where the solver intended.
    const churned: 0 | 1 = rng.fork(`label${index}`).chance(baseProbability) ? 1 : 0;
    return { ...draft, baseProbability, churned };
  });

  const churners = customers.filter((customer) => customer.churned === 1).length;
  return {
    customers,
    intercept,
    baseValue: logit(churners / customers.length),
    realisedChurnRate: churners / customers.length,
  };
}
