/**
 * Generate `.env.example` and the environment reference table from `env.ts`.
 *
 * The specification lives in one place, so the template and the documentation
 * cannot drift away from the code that actually reads the variables.
 *
 *   npx tsx scripts/generate-env-docs.ts
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { ENV_SPECS, type EnvVarSpec } from "../src/lib/env-specs";

const HEADER = `# Environment configuration
#
# Generated by \`npx tsx scripts/generate-env-docs.ts\` from src/lib/env-specs.ts.
# Do not edit by hand: change the specification and regenerate.
#
# Copy to \`.env.local\` for local development:
#   cp .env.example .env.local
#
# Only variables marked "browser safe" may ever reach the client. Everything
# else is read on the server and must be treated as a secret if marked required.
`;

function template(): string {
  const required = ENV_SPECS.filter((spec) => spec.required);
  const optional = ENV_SPECS.filter((spec) => !spec.required);

  const render = (specs: readonly EnvVarSpec[]) =>
    specs
      .map((spec) => {
        const comment = spec.purpose.replace(/\s+/g, " ").trim();
        const lines = [
          `# ${comment}`,
          `# Source: ${spec.source}  |  Read by: ${spec.usedBy}`,
        ];
        // A required variable is left empty in the template even when a default
        // is known, so it has to be set deliberately. The default is shown as a
        // comment so the reader is not left guessing.
        if (spec.required && spec.defaultValue !== undefined) {
          lines.push(`# Suggested: ${spec.defaultValue}`);
          lines.push(`${spec.name}=`);
        } else {
          lines.push(`${spec.name}=${spec.defaultValue ?? ""}`);
        }
        lines.push("");
        return lines.join("\n");
      })
      .join("\n");

  return [
    HEADER,
    "# ---------------------------------------------------------------------------",
    "# Required",
    "# ---------------------------------------------------------------------------",
    "",
    render(required),
    "# ---------------------------------------------------------------------------",
    "# Optional — shown with their default value",
    "# ---------------------------------------------------------------------------",
    "",
    render(optional),
  ].join("\n");
}

function reference(): string {
  const rows = [...ENV_SPECS]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (spec) =>
        `| \`${spec.name}\` | ${spec.required ? "yes" : "no"} | \`${
          spec.defaultValue ?? "—"
        }\` | ${spec.browserSafe ? "yes" : "no"} | ${spec.usedBy} | ${spec.purpose
          .replace(/\s+/g, " ")
          .trim()} |`,
    );

  return [
    "# Environment reference",
    "",
    "Generated by `npx tsx scripts/generate-env-docs.ts` from `src/lib/env-specs.ts`.",
    "That file is the single source of truth for configuration; this table and",
    "`.env.example` are both derived from it.",
    "",
    "| Variable | Required | Default | Browser safe | Read by | Purpose |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "## Notes",
    "",
    "- `SESSION_SECRET` must be at least 32 characters. Rotating it invalidates",
    "  every existing session, so users are signed out.",
    "- `DATABASE_URL` is optional locally because the application falls back to an",
    "  embedded PostgreSQL build (PGlite) under `.data/postgres`. Production must",
    "  set it to a real PostgreSQL server.",
    "- `EMAIL_PROVIDER=log` writes password reset messages to the server log",
    "  instead of sending them. That is acceptable for local work and is not",
    "  acceptable in production, where `EMAIL_PROVIDER_API_KEY` must be set.",
    "- `ML_SERVICE_API_KEY` must match the service's `ML_API_KEY` when the service",
    "  runs with `ML_REQUIRE_API_KEY=true`.",
    "",
  ].join("\n");
}

async function main() {
  const envPath = path.resolve(".env.example");
  const referencePath = path.resolve("ENVIRONMENT.md");
  await writeFile(envPath, template(), "utf8");
  await writeFile(referencePath, reference(), "utf8");
  process.stdout.write(
    `Wrote ${path.relative(process.cwd(), envPath)} and ${path.relative(
      process.cwd(),
      referencePath,
    )} from ${ENV_SPECS.length} variable specification(s).\n`,
  );
}

main().catch((error: unknown) => {
  process.stderr.write(
    `${error instanceof Error ? error.message : String(error)}\n`,
  );
  process.exit(1);
});
