"""Artifact storage and model loading.

Model artifacts are written by the training pipeline and read back here. Every
load validates that the artifact is internally consistent, because a prediction
must always be traceable to the exact model and preprocessing that produced it.
"""

from __future__ import annotations

import json
import re
import threading
from datetime import datetime
from typing import Any

import joblib

from .config import settings
from .pipeline.preprocessing import PreprocessingError, load_preprocessing
from .schemas import EncodedFeature, PreprocessResult

#: Model ids are filesystem-safe identifiers generated by this service. Anything
#: else is rejected before it reaches the filesystem, which closes off path
#: traversal through an id supplied by a client.
SAFE_ID = re.compile(r"^[a-zA-Z0-9_-]{1,128}$")

_WRITE_LOCK = threading.Lock()


class ArtifactError(RuntimeError):
    """Raised when a stored artifact is missing or unusable."""


def assert_safe_id(value: str, field_name: str = "id") -> str:
    """Reject identifiers that could escape the artifact directory."""
    if not value or not SAFE_ID.match(value):
        raise ArtifactError(
            f"Invalid {field_name}. It must contain only letters, digits, "
            "hyphens and underscores."
        )
    return value


class LoadedModel:
    """A trained model with the preprocessing and metadata it was fitted with."""

    def __init__(self, model_id: str, payload: dict[str, Any]) -> None:
        self.model_id = model_id
        self.pipeline = payload.get("pipeline")
        self.model_type: str = payload.get("model_type", "")
        self.version: str = payload.get("version", "")
        self.preprocessing_id: str = payload.get("preprocessing_id", "")
        self.random_seed: int = int(payload.get("random_seed", 0) or 0)
        self.trained_at: str = payload.get("trained_at", "")
        self.best_params: dict[str, Any] = payload.get("best_params", {}) or {}

        if self.pipeline is None:
            raise ArtifactError(f"Model '{model_id}' has no fitted pipeline.")
        if not self.model_type or not self.version:
            raise ArtifactError(f"Model '{model_id}' is missing required metadata.")

    @property
    def steps(self) -> dict[str, Any]:
        return dict(getattr(self.pipeline, "named_steps", {}))

    @property
    def estimator(self) -> Any:
        return self.pipeline.named_steps["model"]


class ModelStore:
    """Filesystem-backed artifact store with an in-process cache."""

    def __init__(self) -> None:
        self._cache: dict[str, tuple[float, LoadedModel]] = {}
        self._lock = threading.Lock()

    # -- model artifacts ---------------------------------------------------

    def model_path(self, model_type: str, version: str) -> str:
        assert_safe_id(model_type, "model type")
        assert_safe_id(version, "model version")
        return str(
            settings.artifact_dir / "models" / f"{model_type}-{version}.joblib"
        )

    def _resolve_model_file(self, model_id: str):
        """Locate an artifact file, accepting an id with or without extension."""
        assert_safe_id(model_id.replace(".joblib", ""), "model id")
        name = model_id if model_id.endswith(".joblib") else f"{model_id}.joblib"
        return settings.artifact_dir / "models" / name

    def load_model(self, model_id: str) -> LoadedModel:
        """Load a model by its ``<model_type>-<version>`` artifact id."""
        path = self._resolve_model_file(model_id)
        if not path.exists():
            raise ArtifactError(
                f"Model '{model_id}' was not found. It may have been removed, or "
                "the ML service may be pointing at a different artifact "
                "directory."
            )

        mtime = path.stat().st_mtime
        with self._lock:
            cached = self._cache.get(model_id)
            if cached and cached[0] == mtime:
                return cached[1]

        try:
            payload = joblib.load(path)
        except Exception as exc:  # noqa: BLE001
            raise ArtifactError(
                f"Model '{model_id}' could not be loaded: {exc}"
            ) from exc

        loaded = LoadedModel(model_id, payload)
        with self._lock:
            self._cache[model_id] = (mtime, loaded)
        return loaded

    def invalidate(self, model_id: str) -> None:
        with self._lock:
            self._cache.pop(model_id, None)

    # -- preprocessing artifacts -------------------------------------------

    def load_preprocessing(self, preprocessing_id: str) -> tuple[Any, dict[str, Any]]:
        assert_safe_id(preprocessing_id, "preprocessing id")
        return load_preprocessing(preprocessing_id)

    def preprocessing_result(
        self, preprocessing_id: str
    ) -> tuple[PreprocessResult, list[dict[str, Any]]]:
        """Return the stored preprocessing record and its source rows."""
        _preprocessor, metadata = self.load_preprocessing(preprocessing_id)
        payload = {k: v for k, v in metadata.items() if k != "source_rows"}
        rows = metadata.get("source_rows", [])
        result = PreprocessResult.model_validate(payload)
        return result, rows

    def encoded_features(self, preprocessing_id: str) -> list[EncodedFeature]:
        result, _rows = self.preprocessing_result(preprocessing_id)
        return result.encoded_features

    def source_rows(self, preprocessing_id: str) -> list[dict[str, Any]]:
        _preprocessor, metadata = self.load_preprocessing(preprocessing_id)
        return list(metadata.get("source_rows", []))

    # -- plots -------------------------------------------------------------

    def plot_exists(self, name: str) -> bool:
        assert_safe_id(name, "plot name")
        return (settings.artifact_dir / "plots" / name).exists()

    def plot_file(self, name: str):
        assert_safe_id(name, "plot name")
        return settings.artifact_dir / "plots" / name


model_store = ModelStore()


def write_json(path, payload: dict[str, Any]) -> None:
    """Atomically write a JSON document."""
    with _WRITE_LOCK:
        from pathlib import Path

        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_suffix(target.suffix + ".tmp")
        temporary.write_text(
            json.dumps(payload, indent=2, default=str), encoding="utf-8"
        )
        temporary.replace(target)


def utcnow_iso() -> str:
    return datetime.now().isoformat()


__all__ = [
    "ArtifactError",
    "LoadedModel",
    "ModelStore",
    "PreprocessingError",
    "assert_safe_id",
    "model_store",
    "utcnow_iso",
    "write_json",
]
